---
version: "3"
services:
  heroes-crontab-redeem:
    image: node:16
    restart: always
    container_name: heroes-crontab-redeem
    working_dir: /app
    volumes:
      - ./heroes-crontab-redeem:/app
    command: >
      sh -c "yarn install && yarn run start"

  heroes-ingame:
    image: node:16
    restart: always
    container_name: heroes-ingame
    working_dir: /app
    volumes:
      - ./heroes-ingame:/app
    ports:
      - "5555:5555"
    command: >
      sh -c "yarn install && yarn run start"

  heroes-issue:
    image: node:16
    restart: always
    container_name: heroes-issue
    working_dir: /app
    volumes:
      - ./heroes-issue:/app
    command: >
      sh -c "yarn install && yarn run start"

  heroes-metadata:
    image: node:16
    restart: always
    container_name: heroes-metadata
    working_dir: /app
    volumes:
      - ./heroes-metadata:/app
    ports:
      - "5005:5005"
    command: >
      sh -c "yarn install && yarn run start"
